name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        change_path: "src"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        bump_each_commit: true
        format: "${major}.${minor}.${patch}